site_name: 'PoliMi MSc Control Notes - Maintained by: Zihao Zheng'
site_url: https://polimi-msc-control-notes.vercel.app/

nav:
- Advanced Multivariable Control:
    - '1. System Formulation and Equilibrium': 'advanced-multivariable-control/chapter1.md'
    - '2. Stability of Linear Systems': 'advanced-multivariable-control/chapter2.md'
    - '3. Linearization and Stability of Nonlinear Systems': 'advanced-multivariable-control/chapter3.md'
    - '4. Lyapunov Theory': 'advanced-multivariable-control/chapter4.md'
- Dynamics for Electric Machines and Drives:
    - '1. Magenetic Circuits': 'dynamics-for-electric-machines-and-drives/chapter1.md'
    - '2. Dynamics of DC Machine': 'dynamics-for-electric-machines-and-drives/chapter2.md'
    - '3. Basics of Power Converter': 'dynamics-for-electric-machines-and-drives/chapter3.md'


theme:
  name: material
  features:
    - content.tabs.link
    - content.code.copy
    - content.code.select
    - pymdownx.critic 
    - pymdownx.caret
    - pymdownx.keys
    - pymdownx.mark
    - pymdownx.tilde

markdown_extensions:
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - attr_list
  - md_in_html
  - pymdownx.blocks.caption
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - footnotes

plugins:
  - glightbox

extra_javascript:
  - javascripts/mathjax.js
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js