site_name: 'PoliMi MSc Control Notes'
site_url: https://polimi-msc-control-notes.vercel.app/

nav:
- Advanced Multivariable Control:
    - '0. Notations': 'advanced-multivariable-control/notations.md'
    - '1. System Formulation and Equilibrium': 'advanced-multivariable-control/chapter1.md'
    - '2. Stability of Linear Systems': 'advanced-multivariable-control/chapter2.md'
    - '3. Linearization and Stability of Nonlinear Systems': 'advanced-multivariable-control/chapter3.md'
    - '4. Lyapunov Theory': 'advanced-multivariable-control/chapter4.md'
    - '5. Linear Quadratic Problem (LQ)': 'advanced-multivariable-control/chapter5.md'
    - '6. Discreate Time Systems': 'advanced-multivariable-control/chapter6.md'
    - '7. Controller Design (Lyapunov and Backstepping)': 'advanced-multivariable-control/chapter7.md'
    - '8. L-Norm and H-Norm': 'advanced-multivariable-control/chapter8.md'
    - 'E.1 Exercise 1': 'advanced-multivariable-control/exercise1.md'
    - 'E.1 Exercise 2': 'advanced-multivariable-control/exercise2.md'
- Dynamics for Electric Machines and Drives:
    - '1. Magenetic Circuits': 'dynamics-for-electric-machines-and-drives/chapter1.md'
    - '2. Dynamics of DC Machine': 'dynamics-for-electric-machines-and-drives/chapter2.md'
    - '3. Basics of Power Converter': 'dynamics-for-electric-machines-and-drives/chapter3.md'
    - '4. Control of DC Machine': 'dynamics-for-electric-machines-and-drives/chapter4.md'
    - '4. Synchornous Machine and Brushless DC Machine': 'dynamics-for-electric-machines-and-drives/chapter5.md'
    - 'E.2 Exercise 2': 'dynamics-for-electric-machines-and-drives/exercise2.md'
- Robotics:
    - '1. Sensors and Actuators': 'robotics/chapter1.md'
    - '2. Odometry': 'robotics/chapter2.md'

theme:
  name: material
  custom_dir: overrides
  features:
    - content.tabs.link
    - content.code.copy
    - content.code.select
    - pymdownx.critic 
    - pymdownx.caret
    - pymdownx.keys
    - pymdownx.mark
    - pymdownx.tilde
    - search.suggest
    - search.highlight
  palette:

    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default 
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      toggle:
        icon: material/brightness-4
        name: Switch to system preference

markdown_extensions:
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - attr_list
  - md_in_html
  - pymdownx.blocks.caption
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - footnotes

plugins:
  - glightbox
  - search
  - meta

# ## Mathjax <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<
# extra_javascript:
#   - javascripts/mathjax.js
#   - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js
# ## >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>

## Ketax <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<
extra_javascript:
  - javascripts/katex.js
  - https://unpkg.com/katex@0/dist/katex.min.js
  - https://unpkg.com/katex@0/dist/contrib/auto-render.min.js

extra_css:
  - https://unpkg.com/katex@0/dist/katex.min.css
## >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>

extra:
  analytics:
    provider: vercel

